"""Comment & Replies logic done

Revision ID: 5fb59e825334
Revises: 71a45229298c
Create Date: 2026-04-14 16:00:56.382702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb59e825334'
down_revision: Union[str, Sequence[str], None] = '71a45229298c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comment_reactions_user_id_fkey'), 'comment_reactions', type_='foreignkey')
    op.drop_constraint(op.f('comment_reactions_comment_id_fkey'), 'comment_reactions', type_='foreignkey')
    op.create_foreign_key(None, 'comment_reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_reactions', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('comments_video_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('video_reactions_user_id_fkey'), 'video_reactions', type_='foreignkey')
    op.drop_constraint(op.f('video_reactions_video_id_fkey'), 'video_reactions', type_='foreignkey')
    op.create_foreign_key(None, 'video_reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'video_reactions', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('videos_owner_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_owner_id_fkey'), 'videos', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'video_reactions', type_='foreignkey')
    op.drop_constraint(None, 'video_reactions', type_='foreignkey')
    op.create_foreign_key(op.f('video_reactions_video_id_fkey'), 'video_reactions', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(op.f('video_reactions_user_id_fkey'), 'video_reactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('comments_video_id_fkey'), 'comments', 'videos', ['video_id'], ['id'])
    op.drop_column('comments', 'parent_comment_id')
    op.drop_constraint(None, 'comment_reactions', type_='foreignkey')
    op.drop_constraint(None, 'comment_reactions', type_='foreignkey')
    op.create_foreign_key(op.f('comment_reactions_comment_id_fkey'), 'comment_reactions', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(op.f('comment_reactions_user_id_fkey'), 'comment_reactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
